### ISSUE TITLE
Ajout de permissions de groupes pour les données personnels

### ISSUE THREAD

**Issue by jdorel** [ungdev/etuutt-api#2]
Objectif : Pour chaque entrée des données personnels, aller au delà du simple `publique/privé`

Intérêts :
  - Permettre uniquement à ses amis, à des groupes spécifiques (par exemple les bureaux d'assos, les gens avec qui j'ai cours, ...) ou a des applications externes d'accéder à certains données (par exemple mon numéro de téléphone)

Implémentation privilégié : créer une nouvelle table, mettant en relation un champ de l'utilisateur avec un groupe. Plutôt que d'overloader la table utilisateur.

**Comment by ThomasRitaine** [comment]
Implémenté dans ce commit :
[✨ (RGPD) Hide or show some data form a user profil base on groups](https://github.com/ungdev/etuutt-api/commit/89f76d5d8b5cdcdb10dd12d48a8e7b1728d159b9)

Merci !
