### ISSUE TITLE
Library to generate fake data : from fzaninotto/Faker to FakerPHP / Faker 

### ISSUE THREAD

**Issue by ThomasRitaine** [ungdev/etuutt-api#22]
### Why ?
fzaninotto/Faker is deprecated, so we have to move to an other library to generate fake data

### Alternative
FakerPHP / Faker is an alternative
[Link to the GitHub repo](https://github.com/fzaninotto/Faker)
[Link to the doc](https://fakerphp.github.io/)

**Comment by TeddyRoncin** [comment]
Fixed with #38
