### ISSUE TITLE
Crash on database's schema update

### ISSUE THREAD

**Issue by TeddyRoncin** [ungdev/etuutt-api#27]
# Description of the problem
When you execute command `php bin/console doctrine:schema:update --force`, you get the following output :
![image](https://user-images.githubusercontent.com/46007498/164891831-f902ceb6-be76-4f6d-82c0-fd00782f8bbe.png)
There is a SQL syntax error when creating tables.

# Why it happens
`GROUPS` is a reserved keyword in MySQL, and it is also the name of a table.

# Solutions
* The table `groups` could be rename
* The name of the table could be escaped using ` characters

**Comment by ThomasRitaine** [comment]
Salut @TeddyRoncin,
Je n'ai aucune erreur quand je lance cette commande. Tu es bien sur la branche `dev` quand tu l’exécutes ?

**Comment by ThomasRitaine** [comment]
Est-ce que tu peux :

1. T'assurer que tu es sur la branche `dev`

2. Supprimer ta DB
```sh
php bin/console doctrine:database:drop --force
```
3. La recréer
```sh
php bin/console doctrine:database:create
```

4. Remettre à jour le schéma
```sh
php bin/console doctrine:schema:update --force
```

**Comment by TeddyRoncin** [comment]
![image](https://user-images.githubusercontent.com/46007498/165058732-47ccbebe-3406-4710-a63f-c4dd835b4673.png)
Oui, j'ai bien toujours le problème. Après j'utilise une base de données MySQL, alors que par défaut, dans le `.env`, on utilise une base de données PostgreSQL (MySQL est quand même censé être supporté, pour l'utiliser c'est juste une ligne à décommenter dans le `.env`)

**Comment by ThomasRitaine** [comment]
D'accord !
Il faut setup une DB MariaDB
C'est dans le README du repo etuutt-core

**Comment by TeddyRoncin** [comment]
Ok, je fais ça demain, merci !

**Comment by TeddyRoncin** [comment]
Ok, ça a marché, j'avoue que j'ai pas trop compris ce que j'ai changé, j'ai l'impression que mariadb s'était pas installé, alors que je suis presque sûr que j'avais essayé ¯\_(ツ)_/¯

**Comment by ThomasRitaine** [comment]
Ok parfait alors !
Pour éviter ce problème aux prochains, on pourra passer par un setup Docker sur les machines perso ;)
