### ISSUE TITLE
When a field is empty, it is not sent in the responses

### ISSUE THREAD

**Issue by TeddyRoncin** [ungdev/etuutt-api#28]
# Description

Everything is in the title.
Here are 2 screenshots to illustrate (the route is `GET users/{id}`) :
Expected :
![image](https://user-images.githubusercontent.com/46007498/167294016-d06f419d-4cfd-4762-91cd-1c6be384798d.png)
Actual :
![image](https://user-images.githubusercontent.com/46007498/167294068-78ef3562-6e98-4718-a889-153e3582c720.png)

# How to fix it

There is a property called `skip_null_values` which should be set to false in the `normalization_context` of the call to `ApiResource` in the entities.
Here is a screenshot of a fixed file and of a non-fixed file (Entity/User.php) :
Fixed :
![image](https://user-images.githubusercontent.com/46007498/167294265-ec4434b5-0d45-47f0-970e-7a4aaea74f2b.png)
Actual :
![image](https://user-images.githubusercontent.com/46007498/167294230-0ac641a6-04c2-470f-a91b-77f2a4ca02ac.png)

**Comment by ThomasRitaine** [comment]
Ok c'est très clair.
Super ticket @TeddyRoncin ! 🎉

Je te laisse faire la PR pour le corriger
